precision: bf16-mixed
device: cpu
train:
  training_files: 
    - /home/mittagessen/ladas/train.lst
  evaluation_files: 
    - /home/mittagessen/ladas/val.lst
  output: /home/mittagessen/dfine/
  class_mapping:
    - AdvertisementZone
    - DigitizationArtefactZone
    - DropCapitalZone
    - FigureZone
    - FigureZone-FigDesc
    - FigureZone-Head
    - FormZone
    - GraphicZone
    - GraphicZone-Decoration
    - GraphicZone-FigDesc
    - GraphicZone-Head
    - GraphicZone-Part
    - GraphicZone-TextualContent
    - MainZone-Continued
    - MainZone-Date
    - MainZone-Entry
    - MainZone-Head
    - MainZone-Lg
    - MainZone-ListItem
    - MainZone-Other
    - MainZone-P
    - MainZone-Signature
    - MainZone-Sp
    - MainZone-Maths
    - MarginTextZone-ManuscriptAddendum
    - MarginTextZone-Notes
    - MarginTextZone-ContinuedNotes
    - MusicZone
    - NumberingZone
    - QuireMarksZone
    - RunningTitleZone
    - StampZone
    - StampZone-Sticker
    - TableZone
    - TableZone-Head
    - TitlePageZone
    - TitlePageZone-Index
  epochs: 24
  lrate: 1e-4
  schedule: constant
  warmup: 1000
  augmentation: true
  validate_before_train: false
  num_top_queries: 300
